[versions]
spring-boot = "4.1.0"
spring-dependency-management = "1.1.7"
spotless = "8.9.0"
google-java-format = "1.36.1"
springdoc = "3.0.3"

[libraries]
springdoc-openapi-starter-webmvc-scalar = { module = "org.springdoc:springdoc-openapi-starter-webmvc-scalar", version.ref = "springdoc" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
