-- ============================================================================
-- V4: 사람이 읽는 이름을 한국어 사전순으로 정렬한다 (MS2-143, 스프린트4 버그 수정 MS2-144)
--
-- 문제: 고객 목록의 순서가 한국어 사전순이 아니었다. 정렬은 전부 DB가 하는데
--   (CustomerRepository의 파생 쿼리 order by name, 자바 계층 재정렬 없음)
--   DB collation이 en_US.utf8이라 '아크메 주식회사'가 '베타 스튜디오'보다 앞에 왔다.
--   한글 사전순은 ㅂ이 ㅇ보다 앞이라 반대가 맞다.
--
-- 범위 밖 (이관, 누락 아님):
--   - 이름 컬럼의 인덱스: 지금 필요한 곳이 없다. 아래 "인덱스를 만들 때" 참조
--   - DB 전체 collation 변경: 아래 "왜 컬럼 레벨인지" 참조
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 왜 C가 아니라 ICU 한국어 로케일인지
--
-- 한글 완성형은 코드포인트 순서가 곧 자모 순서라 C로도 한글끼리는 사전순이 맞다.
-- 하지만 C는 바이트 순서라 라틴 문자에서 대문자가 소문자보다 통째로 앞선다
-- ('Acme Corp' < 'ZeroBase' < 'acme corp'). 인수 기준의 "영문, 숫자가 섞인
-- 이름도 납득 가능한 순서"에 걸린다. ICU 한국어 로케일은 대소문자를 묶어 정렬하고
-- 한글을 라틴보다 앞에 둔다 (실측: 가나다 | 나비 | 힘찬 | acme corp | Beta Corp).
--
-- 로케일 없는 und-x-icu도 대소문자는 묶지만 라틴을 한글보다 앞에 둔다. 한국어
-- 화면에는 ko-KR이 맞다.
--
-- 한국어 로케일을 걸면 영문 이름이 이상해지지 않나 -- 그렇지 않다. ICU 로케일은
-- 유니코드 전체 순서표에 그 언어의 조정만 얹는 것이라 라틴 문자끼리의 순서는
-- 건드리지 않는다. 실측으로 ko-KR과 en-US-x-icu가 라틴 입력에 대해 완전히 같은
-- 결과를 낸다. ko가 더하는 조정은 사실상 "한글을 라틴보다 앞에 둔다" 하나다.
--
-- 다만 영문 이름의 순서가 지금과 아주 똑같지는 않다. 기호의 자리와 대소문자를
-- 묶는 방식이 바뀐다 (예: '(Acme)'가 '99 Corp' 앞으로, 'Acme Corp'이
-- 'acme corp' 옆으로). 이것은 로케일 때문이 아니라 glibc 정렬에서 ICU 정렬로
-- 옮긴 결과다. en-US를 골랐어도 영문 부분은 똑같이 바뀐다. 지금 쓰는
-- en_US.utf8도 바이트 순서가 아니라 이미 언어 인식 정렬이므로, 이 변경은
-- "정렬 없음 -> 정렬 있음"이 아니라 규칙을 갈아타는 것이다.
--
-- 왜 ko-KR-x-icu를 직접 쓰지 않고 이름을 만드는지
--
-- '-x-icu' collation들은 initdb가 그 환경의 ICU에서 발견한 로케일 목록으로 만든
-- 것이라, 이미지나 호스트가 바뀌면 그 이름이 없을 수 있다. CREATE COLLATION은
-- ICU 라이브러리만 있으면 되고 로케일 목록에 기대지 않는다. 배포 환경이 생겨
-- 이미지가 바뀌어도 이 마이그레이션이 그대로 돈다.
-- (실측: 이 정의와 ko-KR-x-icu의 정렬 결과가 동일하다)
--
-- deterministic = true를 명시하는 이유: 기본값이지만, 비결정적 collation은
-- =, GROUP BY, 유니크 판정의 의미까지 바꾼다. 이 컬럼들은 그 의미가 바뀌면 안 되므로
-- 의도를 값으로 박아 둔다.
-- ----------------------------------------------------------------------------
CREATE COLLATION korean (provider = icu, locale = 'ko-KR', deterministic = true);

-- ----------------------------------------------------------------------------
-- 왜 컬럼 레벨인지
--
-- DB 레벨(initdb --icu-locale)은 근본적이지만 기존 DB를 in-place로 못 바꾼다.
-- 팀원 전원이 postgres-data 볼륨을 지워야 하고, docker-compose.yml과
-- TestcontainersConfiguration 양쪽을 계속 맞춰 둬야 하며, 어긋나면 로컬과 CI의
-- 정렬이 갈린다. 게다가 PK 인덱스까지 전부 ICU 의존이 된다.
--
-- 쿼리 레벨(ORDER BY name COLLATE ...)은 파생 쿼리를 네이티브 쿼리로 바꿔야 하고
-- 정렬 규칙이 리포지터리 메서드마다 흩어진다.
--
-- 컬럼 레벨은 이 파일 하나로 끝나고 기존 DB에도 migrate로 그냥 적용된다.
-- varchar -> varchar에 USING이 없어 binary coercible이라 테이블 rewrite도 없다.
--
-- 대상은 사람이 읽는 이름 컬럼이다. 지금 정렬 쿼리가 걸린 것은 customer.name
-- 하나지만, organization.name과 billable_metric.name도 화면에 이름으로 나가는
-- 값이라 목록 정렬이 붙는 순간 같은 버그가 그대로 재발한다. 세 곳을 함께 맞춰 둔다.
--
-- 식별자 컬럼은 제외한다: billable_metric.code(PK, price_policy/price_rate가 FK로
-- 참조), event_type, aggregation, target_property, usage_event.transaction_id(PK).
-- 기계가 매칭하는 값이라 언어별 정렬이 의미가 없고, PK 인덱스가 물려 있어 collation을
-- 바꾸면 인덱스 재빌드 대상이 된다.
--
-- [인덱스를 만들 때] 지금 이 세 컬럼에는 인덱스가 없다. 나중에 이름으로 인덱스를
-- 만들면 두 가지가 따라온다.
--   1) ICU 라이브러리 버전이 바뀌면 정렬 순서가 미세하게 달라질 수 있어 REINDEX가
--      필요하다 (조치 후 ALTER COLLATION korean REFRESH VERSION). 인덱스가 없는
--      지금은 재빌드할 대상 자체가 없다
--   2) LIKE 접두 검색용 인덱스는 기본 collation이 아닌 컬럼이라 varchar_pattern_ops가
--      따로 필요하다
-- ----------------------------------------------------------------------------
ALTER TABLE customer        ALTER COLUMN name TYPE VARCHAR COLLATE korean;
ALTER TABLE organization    ALTER COLUMN name TYPE VARCHAR COLLATE korean;
ALTER TABLE billable_metric ALTER COLUMN name TYPE VARCHAR COLLATE korean;
