ALTER TABLE customer RENAME CONSTRAINT customer_org_id_unique TO customer_organization_id_unique;
ALTER TABLE event RENAME CONSTRAINT event_customer_same_org TO event_customer_same_organization_fk;
ALTER TABLE price_policy RENAME CONSTRAINT price_policy_metric_same_org TO price_policy_billable_metric_same_organization_fk;
ALTER TABLE invoice RENAME CONSTRAINT invoice_customer_same_org TO invoice_customer_same_organization_fk;
ALTER TABLE invoice_line RENAME CONSTRAINT invoice_line_invoice_same_org TO invoice_line_invoice_same_organization_fk;
ALTER TABLE price_rate RENAME CONSTRAINT price_rate_policy_fk TO price_rate_price_policy_same_organization_fk;

ALTER TABLE invoice RENAME CONSTRAINT invoice_org_id_unique TO invoice_organization_id_unique;
ALTER TABLE invoice_line RENAME CONSTRAINT invoice_line_metric_unique TO invoice_line_invoice_billable_metric_dimension_values_unique;
ALTER TABLE invoice RENAME CONSTRAINT invoice_customer_period_unique TO invoice_organization_customer_period_unique;
ALTER TABLE invoice RENAME CONSTRAINT invoice_period_format TO invoice_period_check;

ALTER TABLE price_policy RENAME CONSTRAINT price_policy_metric_code_not_null TO price_policy_billable_metric_code_not_null;
ALTER TABLE price_rate RENAME CONSTRAINT price_rate_metric_code_not_null TO price_rate_billable_metric_code_not_null;
ALTER TABLE invoice_line RENAME CONSTRAINT invoice_line_metric_code_not_null TO invoice_line_billable_metric_code_not_null;
